#Include "totvs.ch"
#Include "tlpp-core.th"

NAMESPACE treinamento.api


/*/{Protheus.doc} U_GET_FORNECEDORES as logical
    Exemplo de API com paginação
    @type  Function
    @author Fernando rodrigues
    @since 15/07/2026
    /*/
@get(endpoint='/treinamento/listafornecedores')
Function U_GET_FORNECEDORES as logical
    Local lRpc          as logical
    Local nError        as numeric
    Local cError        as character

    Local jQueryStr     as json
    Local jResp         as json

    Local oAdapter      as object
    Local cSql          as character
    Local cWhere        as character
    Local cEstado       as character
    Local cCidade       as character
    Local nSize         as numeric
    Local nPage         as numeric
    Local cOrder        as character
    Local cSearch       as character
    
    try
        jQueryStr       := oRest:getQueryRequest()

        cEstado         := jQueryStr['estado'   ]
        cCidade         := jQueryStr['cidade'   ]
        nSize           := jQueryStr['pageSize' ]
        nPage           := jQueryStr['page'     ]
        cOrder          := jQueryStr['order'    ]
        cSearch         := jQueryStr['search'   ]

        nSize           := if(empty(nSize),10,nSize)
        nPage           := if(empty(nPage),1 ,nPage)

        If type('cEmpAnt') <> 'C'
            rpcSetEnv('99', '01')
            lRpc := .T.
        EndIf

        cSql        := "SELECT #QueryFields# FROM " + retSqlName('SA2') + " SA2"
        cSql        += CRLF + "WHERE #QueryWhere# "

        cWhere      := "D_E_L_E_T_ = ' ' "

        If .not. empty(cEstado)
            cWhere  += CRLF + "AND A2_EST = '" + cEstado + "' "
        EndIf

        If .not. empty(cCidade)
            cWhere += CRLF + "AND A2_MUN LIKE '%" + cCidade + "%'"
        EndIf

        If .not. empty(cSearch)
            cWhere += CRLF + "AND A2_NOME LIKE '%" + cSearch + "%'"
        EndIf

        oAdapter        := fwAdapterBaseV2():new('GET',.T.)
        oAdapter:addMapFields('cod'         ,'A2_COD'   ,.T.,.T.,{'A2_COD','C',06,00}, 'SA2.A2_COD') // CASO O CAMPO NÃO EXISTA NA SX3 COLOCAR SEUS PARAMETROS 
        oAdapter:addMapFields('loja'        ,'A2_LOJA'  ,.T.)
        oAdapter:addMapFields('nome'        ,'A2_NOME'  ,.T.)
        oAdapter:addMapFields('fantasia'    ,'A2_NREDUZ',.T.)
        oAdapter:addMapFields('endereco'    ,'A2_END'   ,.T.)

        oAdapter:setQuery(cSql)
        oAdapter:setWhere(cWhere)
        oAdapter:setPageSize(nSize)
        oAdapter:setPage(nPage)
        oAdapter:setOrder(cOrder)

        If oAdapter:execute()

            oAdapter:fillGetResponse()
            cResult := oAdapter:getJsonResponse()

            oRest:setResponse(cResult)

        Else
            
            nError          := oAdapter:getCode()
            cError          := oAdapter:getMessage()

            jResp           := jsonObject():new()
            jResp['error']  := cError

            oRest:setFault(jResp:toJson())

        EndIf

    catch err

        cError          := err:errorstack

        jResp           := jsonObject():new()
        jResp['error']  := cError

        oRest:SetFault(jResp:toJson())

    endtry

    If lRpc
        rpcSetEnv()
    EndIf
    

Return .T.
