#Include "totvs.ch"
#Include "tlpp-core.th"



Class  aula_05 from fwAdapterBaseV2
    
    public method new() constructor

    @get('/trenamento/list/fornecedores')
    public method lista_fornecedores() as logical

    @post('/treinamento/fornecedores/new')
    public method incluir_fornecedores() as logical

EndClass

method new() class aula_05; return self

method incluir_fornecedores() class aula_05

    Local lRpc      as logical
    Local jBodyReq  as json
    Local aDados    as array
    Local nOpc      as numeric
    Local cNome     as character
    Local cNomeRed  as character
    Local cTipo     as character
    Local cCgc      as character
    Local cEnd      as character
    Local cBairro   as character
    Local cCidade   as character
    Local cEstado   as character
    Local cEmail    as character
    Local cTel      as character
    Local cCodMun   as character
    Local cError    as character
    Local jResp     as json

    Private err            as object
    Private lMsErroAuto    as Logical

    If type('cEmpAnt') <> 'C'
        rpcSetEnv('99','01')
        lRpc        := .T.
    EndIf

    try

        jBodyReq     := jsonObject():new()
        jBodyReq:fromJson(oRest:getBodyRequest())

        cNome      := jBodyReq['nome'          ]
        cNomeRed   := jBodyReq['nome_fantasia' ]
        cTipo      := jBodyReq['tipo'          ]
        cCgc       := jBodyReq['cgc'           ]
        cEnd       := jBodyReq['endereco'      ]
        cBairro    := jBodyReq['bairro'        ]
        cCidade    := jBodyReq['cidade'        ]
        cEstado    := jBodyReq['estado'        ]
        cEmail     := jBodyReq['email'         ]
        cTel       := jBodyReq['telefone'      ]


        cCgc       := strTran(strTran(strTran(cCgc,'.',''),'-',''),'/','')
        cTel       := strTran(strTran(strTran(strTran(cTel,' ',''),'-',''),'(',''),')','')

        CC2->(dbSetOrder(4), dbSeek(xFilial(alias())+cEstado+cCidade))
        cCodMun     := CC2->CC2_CODMUN

        aDados  := {{"A2_LOJA"  ,"01"       ,NIL},;
                    {"A2_NOME"  ,cNome      ,Nil},;
                    {"A2_NREDUZ",cNomeRed   ,Nil},;
                    {"A2_CGC"   ,cCgc       ,Nil},;
                    {"A2_TIPO"  ,cTipo      ,Nil},;
                    {"A2_END"   ,cEnd       ,Nil},;
                    {"A2_BAIRRO",cBairro    ,Nil},;
                    {"A2_EST"   ,cEstado    ,Nil},;
                    {"A2_MUN"   ,cCidade    ,Nil},;
                    {"A2_COD_MUN",cCodMun    ,Nil},;
                    {"A2_EMAIL" ,cEmail     ,Nil},;
                    {"A2_TEL"   ,cTel       ,Nil}}
        
        nOpc    := 3

        lMsErroAuto := .F.

        msExecAuto({|x,y| mata020(x,y) }, aDados, nOpc)

        If lMsErroAuto
            mostraErro('\data\','erro_sa2.txt')
            cError  := memoread('\data\erro_sa2.txt')

            err             := errorClass():new()
            err:description := cError

            throw err

        EndIf

        jResp   := jsonObject():new()
        jResp['codigo'] := SA2->A2_COD
        jResp['loja']   := SA2->A2_LOJA
        jResp['nome']   := SA2->(AllTrim(A2_NOME))
        jResp['status'] := 'FONECEDOR INCLUIDO COM SUCESSO!!'

        oRest:setResponse(jResp:toJson())

    catch err
        cError  := err:description

        jResp           := jsonObject():new()
        jResp['error']  := cError

        oRest:SetFault(jResp:toJson())

    endtry


    If lRpc
        rpcClearEnv()
    EndIf

    

return .T.

method lista_fornecedores() class aula_05
    Local lRpc
    Local nError        as numeric
    Local cError        as character

    Local jQueryStr     as json
    Local jResp         as json

    Local cSql          as character
    Local cWhere        as character
    Local cEstado       as character
    Local cCidade       as character
    Local nSize         as numeric
    Local nPage         as numeric
    Local cOrder        as character
    Local cSearch       as character
 

    If type('cEmpAnt') <> 'C'
        rpcSetEnv('99','01')
        lRpc        := .T.
    EndIf

    try

        jQueryStr       := oRest:getQueryRequest()

        cEstado         := jQueryStr['estado'   ]
        cCidade         := jQueryStr['cidade'   ]
        nSize           := jQueryStr['pageSize' ]
        nPage           := jQueryStr['page'     ]
        cOrder          := jQueryStr['order'    ]
        cSearch         := jQueryStr['search'   ]

        nSize           := if(empty(nSize),10,nSize)
        nPage           := if(empty(nPage),1 ,nPage)

        cSql        := "SELECT #QueryFields# FROM " + retSqlName('SA2') + " SA2"
        cSql        += CRLF + "WHERE #QueryWhere# "

        cWhere      := "D_E_L_E_T_ = ' ' "

        If .not. empty(cEstado)
            cWhere  += CRLF + "AND A2_EST = '" + cEstado + "' "
        EndIf

        If .not. empty(cCidade)
            cWhere += CRLF + "AND A2_MUN LIKE '%" + cCidade + "%'"
        EndIf

        If .not. empty(cSearch)
            cWhere += CRLF + "AND A2_NOME LIKE '%" + cSearch + "%'"
        EndIf

        _Super:new('GET', .T.)

        ::addMapFields('cod'         ,'A2_COD'   ,.T.,.T.,{'A2_COD','C',06,00}, 'SA2.A2_COD') // CASO O CAMPO NÃO EXISTA NA SX3 COLOCAR SEUS PARAMETROS 
        ::addMapFields('loja'        ,'A2_LOJA'  ,.T.)
        ::addMapFields('nome'        ,'A2_NOME'  ,.T.)
        ::addMapFields('fantasia'    ,'A2_NREDUZ',.T.)
        ::addMapFields('endereco'    ,'A2_END'   ,.T.)

        ::setQuery(cSql)
        ::setWhere(cWhere)
        ::setPageSize(nSize)
        ::setPage(nPage)
        ::setOrder(cOrder)

        If ::execute()

            ::fillGetResponse()
            oRest:setResponse(::getJsonResponse())

        Else
            
            nError          := ::getCode()
            cError          := ::getMessage()

            jResp           := jsonObject():new()
            jResp['error']  := cError

            oRest:setFault(jResp:toJson())

        EndIf

    catch err

        cError          := err:errorstack

        jResp           := jsonObject():new()
        jResp['error']  := cError

        oRest:SetFault(jResp:toJson())


    endtry


    If lRpc
        rpcClearEnv()
    EndIf

return .T.
